config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  resources :projects

  root 'welcome#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post, foreign_key: "post_id"
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :author, class_name: "User"
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :technologies_used, presence: true
  validates :name, length: {within: 2..150, too_long: "You're naming a project, not writing a book.", too_short: "You should probably name your project something more distinctive."}
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts,foreign_key: "author_id"
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def author?
    role == "author"
  end

  def editor?
    role == "editor"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper ApplicationHelper
  include Pundit
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_post
  skip_before_action :verify_authenticity_token, only: :update

  def index
    @comments = policy_scope(Comment)
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def new
    @comment = @post.comments.build
  end

  def create
    @comment = @post.comments.build(comment_params)
    if @comment.save
      redirect_to @post, notice: 'Your comment is pending approval.'
      @post.comments << @comment
    else
      redirect_to @post, notice: 'There was a problem saving your comment.'
    end
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(:approved=>params[:approved])
      redirect_to @post, notice: 'Comment has been approved.'
    else
      redirect_to @post, notice: 'There was a problem updating this comment.'
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:post_id, :content, :author, :author_id,
      :author_email, :user_agent, :user_ip, :referrer,
      (:approved if PostPolicy.new(current_user, @post).publish?))
  end

  def find_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < ApplicationController
  def all
    user = User.from_omniauth(request.env["omniauth.auth"])
    if user.persisted?
      flash.notice = "#{user.email}, you are signed in!"
      sign_in_and_redirect user, notice: "#{user.email}, you are signed in!"
    else
      session["devise.user_attributes"] = user.attributes
      redirect_to new_user_registration_url
    end
  end
  alias_method :twitter, :all
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]
  after_action :verify_authorized, except: [:show, :index]
  skip_before_action :verify_authenticity_token, only: :destroy

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
    authorize @post
  end

  # GET /posts/1/edit
  def edit
    authorize @post
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    authorize @post

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
        current_user.posts << @post
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    authorize @post
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    authorize @post
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, (:published if PostPolicy.new(current_user, @post).publish?))
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def create
    @project = Project.new(project_params)
    if @project.save
      flash[:notice] = "Project has been created."
      redirect_to @project
    else
      flash.now[:error] =  "Project could not be saved."
      render :new
    end
  end

  def new
    @project = Project.new
  end

  def index
    @projects = Project.all
  end

  def show
  end

  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, flash[:notice] => "Project has been destroyed."}
      format.json { head :no_content }
    end
  end

  def edit
  end

  def update
    if @project.update_attributes(project_params)
      redirect_to @project, flash[:notice] => "Project was successfully updated."
    else
      render :edit
    end
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :technologies_used)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # translate the rails flash levels to appropriate Zurb Foundation css classes
  def flash_class(level)
    case level
      when :notice then "info"
      when :success then "success"
      when :error then "error"
      when :alert then "warning"
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title><%= content_for?(:title) ? yield(:title) : "Alex Quel Lien" %></title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div>
      <nav class="top-bar" data-topbar>
        <ul class="title-area">
          <li class="name">
            <h1><%= link_to "Portfolio", root_path %></h1>
          </li>
        </ul>
        <section class="left-nav-section">

          <% if current_user.present? %>
          <%= link_to "Finished? Sign out", destroy_user_session_path, method: :delete  %>
          <% else %>
          <%= link_to "New user? Sign up!", new_user_registration_path %>
          <%= link_to "Done that? Sign in", new_user_session_path %>
          <% end %>
        </section>
      </nav>
    </div>
    <!-- provide space for the alert notices -->
    <div class="row">
      <div class="small-12 column">
        <% flash.each do |key, value| %>
        <div class="alert-box round <%= flash_class(key) %>">
          <%= value %>
        </div>
        <% end %>
      </div>
        <div class="row">
          <div class="small-2 column">About Me
          <ul>
            <li><%= link_to "My Blog Posts", posts_path %></li>
            <li><%= link_to "My Projects", projects_path %></li>
          </ul>
          </div>
          <div class="small-10 column"><%= yield %></div>
        </div>
        <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/layouts/backup.html.erb
backup.html.erb
<body>
    <div>
      <nav class="top-bar" data-topbar>
        <ul class="title-area">
          <li class="name">
            <h1><%= link_to "Portfolio", root_path %></h1>
          </li>
        </ul>
        <section class="left-nav-section">
        </section>
      </nav>
    </div>
    <!-- provide space for the alert notices -->
      <div class="row">
      <div class="small-12 column">
        <% flash.each do |key, value| %>
        <div class="alert-box round <%= flash_class(key) %>">
          <%= value %>
        </div>
        <% end %>
      </div>
      <!-- sidebar and main-->
      <div class="row">
        <div class="small-10 column"><%= yield %></div>
        <div class="small-2 column">About Me
        <ul>
          <li><%= link_to "My Blog Posts", posts_path %></li>
          <li><%= link_to "My Projects", projects_path %></li>
        </ul>
        </div>
      </div>
        <%= javascript_include_tag "application" %>
  </body>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
<% if @post.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
  <ul>
    <% @post.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<p>
<div class="row collapse">
  <div class="small-3 column"><%= f.label :title %></div>
  <div class="small-9 column"><%= f.text_field :title %></div>
</div>
</p>
<p>
<div class="row collapse">
  <div class="small-3 column"><%= f.label :body %></div>
  <div class="small-9 column"><%= f.text_field :body %></div>
</div>
</p>
<% if PostPolicy.new(current_user, @post).publish? %>
<p>
<div class="field">
  <%= f.label :published %>
  <%= f.check_box :published %>
</div>
</p>
<% end %>
<p>
<div class="row collapse">
  <div class="small-3 column"><%= f.submit class: "button radius"%></div>
</div>
</p>
<% end %>

app/views/posts/_login.html.erb
<% if current_user.present? %>
  <%= link_to "Finished? Sign out", destroy_user_session_path, method: :delete  %>
<% else %>
  <%= link_to "New user? Sign up!", new_user_registration_path %> <br>
  <%= link_to "Done that? Sign in", new_user_session_path %>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post, class: "button radius" %>
<%= link_to 'Back', posts_path, class: "button radius" %>
<%= link_to 'Destroy', @post, method: :delete, data: { confirm: 'Are you sure?' }, class: "button radius" %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= link_to 'Show', post %></td>
        <% if policy(post).update? %>
          <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <% end %>
        <% if policy(post).destroy? %>
          <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if PostPolicy.new(current_user, @post).create? %>
<%= link_to 'New Post', new_post_path, class: "button radius" %>
<% end %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path, class: "button radius" %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p id="author">
  <strong>By:</strong>
  <%= @post.author.email %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<p id="status">
  <b>Status:</b>
  <%= @post.published? ? "Published" : "Unpublished" %>
</p>


<%= link_to 'Back', posts_path, class: "button radius" %>
<% if policy(@post).update? %>
  <%= link_to 'Edit', edit_post_path(@post), class: "button radius" %>
<% end %>
<% if policy(@post).destroy? %>
  <%= link_to 'Destroy', @post, method: :delete, data: { confirm: 'Are you sure?' }, class: "button radius" %>
<% end %>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
<% if @project.errors.any? %>
<div class="error explanation">
  <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>
  <ul>
    <% @project.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class="field">
  <%= f.label :name %><br />
  <%= f.text_field :name %>
</div>
<div class="field">
  <%= f.label :technologies_used %><br />
  <%= f.text_area :technologies_used %>
</div>
<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/projects/edit.html.erb
<h2>Editing project</h2>

<%= render "form" %>

<%= link_to 'Cancel', projects_path %>

app/views/projects/index.html.erb
<h2>My Portfolio</h2>

<% @projects.each do |project| %>
  <div class="project" id="<%= dom_id(project) %>">
    <h3><%= project.name %></h3>
    <p><%= project.technologies_used %></p>
    <div class="nav">
      <%= link_to 'Show', project %> |
      <%= link_to 'Edit', edit_project_path(project) %> |
      <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
  </div>
<% end %>

<br />
<%= link_to 'New project', new_project_path %>

app/views/projects/new.html.erb
<h2>New project</h2>

<%= render "form" %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<h2><%= @project.name %></h2>
<p>Technologies used: <%= @project.technologies_used %>

<%= link_to "Back", project_path %> |
<%= link_to "Edit", edit_project_path(@project) %> |
<%= link_to 'Destroy', @project, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/welcome/index.html.erb
<h4 align="center">Hi, my name is Alex Quel Lien</h4>
<div></div>

<p>I believe you should hire me. I am very motivated to succeed,
  and I am learning how to make websites look awesome.
  I'm very conscientious, and I try to be thorough in my work.
  I'm willing to admit to and learn from my mistakes,
  and can recognize faults - such as the fact that this webpage is not awesome yet.
  I'm getting there, though!</p>